### ISSUE TITLE
Op code doesn't have cpu version

### ISSUE THREAD

**Issue by LetsGoFir** [Jittor/jrender#1]
After I edit line 3 in `demo1-render.py` to
`jt.flags.use_cuda = 0`
It report this
```
Failed reason:[f 1215 20:35:10.217032 20 op.cc:158] Check failed: flags.get(NodeFlags::_cpu)  Something wrong... Could you please report this issue?
 Op code doesn't have cpu version
```
Do you only support jittor-gpu?

**Comment by zhouwy19** [comment]
Thank you for your reply.

It's because the rendering speed is so slow if use cpu. At present, all papers about differentiable render write cuda code for the rendering process.
