### ISSUE TITLE
Jrender_dataset pose

### ISSUE THREAD

**Issue by kwea123** [Jittor/jrender#14]
https://www.educoder.net/competitions/index/Jittor-3

Are you sure the pose is correct? I plotted the cameras and they are all pointing outwards, which is not reasonable. Also judging from the README result after 50k iters, I'm certain that the pose is wrong, the model is just overfitting.

I didn't participate in the competition, maybe there is some fix during the competition? Can you make sure? Thanks.

**Comment by Jittor** [comment]
The dataset is generated in right-handed coordinate system, which is different from the coordinate system used in Blender. To use our dataset, you should modify the camera space setting, more details please refer to jrender_vol/camera/pinhole.py

**Comment by kwea123** [comment]
Ok, thank you. I didn't find any description in the dataset, and "right-handed coordinate system" generally means [right, down front] axes in all the resources I can found.
Anyway, now I know how to convert the axes using the file you pointed to me.

**Comment by kwea123** [comment]
The training now works for `Coffee`, `Scar` and `Scarf`. However, the pose is still wrong for `Easyship` and `Car`

For example, I plotted the `val` camera poses for `Car`, they are all pointing to a random direction, instead of pointing to the center (the car)
![Screenshot from 2022-08-04 11-30-26](https://user-images.githubusercontent.com/11364490/182750366-d2a45ee3-5ae7-4cb6-a24b-4171ed86173f.png)

On the other hand, the poses for `Scar` is correct like this
![Screenshot from 2022-08-04 11-33-03](https://user-images.githubusercontent.com/11364490/182750522-318965cd-7751-4aa4-b0fc-7ac2dcc07125.png)

Finally I can show you the working scenes to make sure that my training is correct
https://user-images.githubusercontent.com/11364490/182750951-69dfd73a-7f63-4a7d-aa39-ed2e4f373d9b.mp4

I can't get reasonable results on `Easyship` and `Car`, so it must be the problem of the poses. Didn't anyone find any problem in the competition?

**Comment by kwea123** [comment]
I found the problem, it's the focal length (`camera_angle_x`) which is wrong.

For `Easyship` it should be  0.7853981633974483 which is 45 degrees, instead of the original 1.0471975511965976 which is 60 degrees.
For `Car` it should be 1.0471975511965976 which is 60 degrees instead of 1.1344640137963142 which is 65 degrees....

It is surprising to me that this kind of mistake occurs in a competition... hope the competitors are intelligent enough to find this bug.

**Comment by kwea123** [comment]
https://user-images.githubusercontent.com/11364490/183252006-fdd5ce6e-8830-4ff0-b8f2-bd9b4aa5f162.mp4

**Comment by kwea123** [comment]
Since the competitons has ended, I can disclose the solution: the correct fov for `Car` is 60 and for `Easyship` is 45. Also noticed that the top competitors found these correct values too. Congratulations!
