### ISSUE TITLE
NERF实测性能与官宣性能对不上

### ISSUE THREAD

**Issue by zjuwangdong** [Jittor/jrender#5]
您好，我们根据Pytorch版本的NERF[https://github.com/yenchenlin/nerf-pytorch]在V100上实测了Jittor的NERF（lego数据）单卡性能为8.4 FPS，Pyotrch的性能为8 FPS（关闭torch.autograd.set_detect_anomaly()），与Jittor官方数据（1.9倍）差距较大，请问原因可能是啥？

config（lego.txt）设置如下，且accumulation_steps = 1

expname = blender_paper_lego
basedir = ./logs
datadir = ./data/nerf_synthetic/lego
dataset_type = blender

no_batching = True

use_viewdirs = True
white_bkgd = True
lrate_decay = 500

N_samples = 64
N_importance = 128
N_rand = 1024

precrop_iters = 500
precrop_frac = 0.5

half_res = True
testskip=1
faketestskip=8
i_tottest = 400000

**Comment by xin-xinhanggao** [comment]
你好，我们和nerf-pytorch版本的对比是在2021年7月做的，他当时的版本确实比我们慢2倍。

刚刚我看了一下nerf-pytorch的最新代码，他们在4天前修改了run_nerf_helpers.py，增加了一行torch.autograd.set_detect_anomaly(True)，关闭torch.autograd.set_detect_anomaly()确实会让torch快很多。

至于torch.autograd.set_detect_anomaly()在底层代码具体做了些什么，我们团队会进行进一步研究。目前我们的Jittor底层框架也在求导的异常检测等点上进行优化，新版本发布后我们有信心会比Pytorch做得更好。

**Comment by xin-xinhanggao** [comment]
我们在最新的版本中加入了对Nerf的优化，比之前快了很多 感谢持续关注Jrender与JNeRF仓库。
